### ISSUE TITLE
main.go 파일이 작동되지 않습니다.

### ISSUE THREAD

**Issue by sangwoo940** [geeksbaek/archeage-discord-bot#1]
최신버전과 1.5버전을 다 사용해봤습니다.
에러가 계속 나서
go get -u github.com/bwmarrin/discordgo
go get -u github.com/geeksbaek/archeage-go
후에 
go install archeage로 사용하고있는데

C:\Go\src\github.com\gorilla\websocket\client.go:9:2: cannot find package "context" in any of:
        C:\Go\src\context (from $GOROOT)
        C:\Users\h\go\src\context (from $GOPATH)

라고 뜹니다. 버전의 오류인가요?
작성하신 버전이 어떻게되는지 궁금합니다

**Comment by geeksbaek** [comment]
개발은 1.9 버전에서 했던 것으로 기억하는데, 현재 1.11 버전에서 정상 빌드됩니다. 
context 패키지를 못 찾는 것은 go 버전이 낮기 때문으로 보입니다. go 표준 라이브러리에 context 패키지가 추가된 것은 1.7 버전부터입니다.

**Comment by sangwoo940** [comment]
답변 감사드립니다.
1.11버전으로 클린설치 후 build, run 정상적으로 성공하였습니다.
'?캐릭터 캐릭터명@서버' 명령어를 사용하면 무반응인데 새로짜야하는경우인가요?
tools.go 에서 서버명과 파라미터는 바꿔줬습니다.

**Comment by sangwoo940** [comment]
프롬프트를 관리자권한으로 실행하여 go get하니 해결되었습니다
빌드 후 실행하니
error obtaining account details, HTTP 401 Unauthorized, {"code": 0, "message": "401: Unauthorized"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6a3bef]
에러가나오는데 ./archeage-discord-bot -t [TOKEN] 를 프롬프트 명령으로 어떻게 처리해야할까요?

**Comment by geeksbaek** [comment]
봇이 정상적으로 서버에 입장하였는 지 확인 바랍니다. 해당 이슈는 종료합니다.
